# Generated by Django 4.0.7 on 2023-02-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'auctions',
            },
        ),
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.BigIntegerField()),
                ('weighted', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('item_class', models.CharField(max_length=30)),
                ('item_subclass', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('media', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'commodities',
            },
        ),
        migrations.CreateModel(
            name='ItemsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('item_class', models.CharField(max_length=30)),
                ('item_subclass', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'items data',
            },
        ),
        migrations.CreateModel(
            name='ItemsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('media', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'items media',
            },
        ),
    ]
